-- AlterTable
ALTER TABLE `SiteConfig` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `greeting` TEXT NULL,
    ADD COLUMN `history` TEXT NULL,
    ADD COLUMN `mission` TEXT NULL,
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `vision` TEXT NULL;
